services:
  app:
    build: .
    container_name: app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-} # Set your OpenAI API key here
      - PYDANTIC_AI_MODEL=${PYDANTIC_AI_MODEL:-gpt-4o}
    ports:
      - 8501:8501
