name: Dependencies upgrade

on:
  workflow_dispatch:
  schedule:
   - cron: "0 0 1 * *" # Once a month

concurrency:
 group: ${{ github.ref }}-${{ github.workflow }}
 cancel-in-progress: true

jobs:
  flake-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5

    # https://docs.astral.sh/uv/concepts/projects/#upgrading-locked-package-versions
    - run: uv lock --upgrade

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      id: cpr
      with:
        title: "[Automated] Dependencies upgrade"
        commit-message: "[Automated] Dependencies upgrade"
        branch: "auto/uv-sync-upgrade"
        add-paths: uv.lock
        delete-branch: true
        labels: |
            automated pr
        draft: true
             
    - name: Create PR output
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
